### ISSUE TITLE
extra.channel on ComfyJS.onJoin()

### ISSUE THREAD

**Issue by pookiepew** [instafluff/ComfyJS#13]
Is it possible to add extra in the onJoin( user, self ) so we can react to users joining in different channels with ComfyJS.Say( msg, channel ) if the bot is in multiple channels ? 

I have a function running in onJoin checking if user birthday = today. I would like to send a message to the channel the user joined if that makes sense.

**Comment by instafluff** [comment]
Fixed in 1f11535d1e89b53e4b8d49245bd2b7e5f4a642fd
