### ISSUE TITLE
Unhandled error when trying to create a custom reward

### ISSUE THREAD

**Issue by SrManinka** [instafluff/ComfyJS#27]
When i tried to create a custom reward that already existed, it sais

```javascript
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.CreateChannelReward (..\node_modules\comfy.js\app.js:648:29)
```
looking at that file, i think that if the code below were used after line 646, it could help understanding the cause.

```javascript
if(custom.message == "CREATE_CUSTOM_REWARD_DUPLICATE_REWARD"){
 throw new Error( "Duplicated Custom Reward" ) 
}
return custom.data[ 0 ];
```

**Comment by PierreRock** [comment]
had a similar issue. To me, reason was that I capped my channel custom reward. you may only have 50.

**Comment by SrManinka** [comment]
Actually i found out there are many of those unhandled errors, but I won't keep complaining. I really appreciate what those guys made so far. Thanks, instafluff and friends!
