### ISSUE TITLE
TypeError: Cannot read propery 'url_1x' of null

### ISSUE THREAD

**Issue by PierreRock** [instafluff/ComfyJS#31]
encountered this error when trying to read channel point rewards.

Been able to solve it by handling null value of reward.image property in app.js (see my proposed fix below)

![image](https://user-images.githubusercontent.com/29356866/114485243-954d1f00-9bd9-11eb-84e5-d8769411c977.png)

**Comment by instafluff** [comment]
Fixed in 92fc6ad996d2d4a466d25103b191e80c0397125e !
